# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79d6c840719f649f59d148c6aa6065a6e00ac2130b5ccf1cc035382475f12eca6a80b3501e6dc3f1cb9aebfb891db46a8a5306d594da6c87c0feb8a82c92be33

test:
  secret_key_base: 2699b609f564d00e57c8703f80a21f07484dcef21e5c292da9b7d62f598957f07004e8d2305a931a90088ab8b0c692be1dcf33b5fd8ac660590af9ab01c8da33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
